### ISSUE TITLE
 Building a page for each job so it has it's own unique URL + SEO

### ISSUE THREAD

**Issue by ChaseDudas** [Denver-Devs/denverdevs.org#128]
**Features being implemented**
 Build a page for each job so it has its own unique URL + SEO
 Allow for a brief description of the job (if we build individual job pages)
 Allow for a brief company or job summary

**Describing the solution**
Each job would have its own page under https://denverdevs.org/jobs/[id]. The job page would showcase information already found in the preview card plus a company summary and job description fields. The jobs page is meant to give the user more details about the job and even possibly the company who posted the job. Each page will have a unique title and description in the header for SEO purposes.

**Describe alternatives you've considered**
I am open to suggestions about any alternatives to my implementation :)

**Additional context**
Style-wise, I am going off of features already present on the site. I am open to any design suggestions as well.

**Comment by danhannigan** [comment]
Hey @ChaseDudas! Thanks for hopping in to look at some new features and enhancements to take on. A few thoughts on this one: 

Originally I actually had a full-fledged Markdown editor on the job post page to let folks add in whatever they wanted but I removed that for the sake of simplicity (and pushing for an MVP) — one of the main considerations I had is that if we allowed folks to provide a description we should logically allow them to edit the post, too. Which led into a bit of a wormhole on: what's that look like for the approval process (since it's all manual approval), do only certain folks get to edit, etc. Just something for us to think about on that. 

To the other part about the company summary I'd say let's leave that off for now. That addition exposes some interesting workflows around company associations (let's say two different people are posting for the same company, do we give them a "company profile" to assign themselves to, for example), different tables, so on that I don't know would really give us a good payoff for our efforts at the moment. 

Thoughts? Ideas?

**Comment by ChaseDudas** [comment]
Of course @danhannigan! I am thrilled to be contributing.

I see the rabbit hole you are pointing out. I think having a markdown editor makes sense because a text area would take away some of the formatting niceties. Here are some rough thoughts:
- Could it be that whoever posted the job could have edit access to the description once approved? 
- Is editing something that could also hold off for now?
-  If someone needs a change, could they submit a manual request somewhere? 

How would you see the page's SEO description taking shape if the description is markdown? Should we have one standard format? Something like " ... role posted by ... on the Denver Devs Job Board"? or maybe the first n chars of the description?

Thank you for the suggestion. I am happy to leave the company summary out. I think it brings in more complexity than is needed right now.

**Comment by danhannigan** [comment]
Good questions! I'll address them in order: 

- Pretty sure we could get it set up that whoever posted the job would be able to edit it, I have the same access right now with them being able to delete it. My only concern (and I'll admit it's maybe a bit over-protective) is having someone do any kind of nefarious edits. I could have it shoot off an email to me whenever someone edits though 🤔 that might help mitigate some issues. We'd have to let them know though that "hey, thanks for the edit, it'll update when we redeploy the site" (since I'm moving back to SSG for the posts)

- We could definitely hold off on edit access for now — usually what I've had happen whenever folks need to make updates is that they either delete + recreate their post or they'll email me and let me know they need an update. I can then hop into the database and fiddle with things. (combo'd the last two into one answer) 

As far as the page SEO description... I think simplicity is our friend here so yeah some standard string that gets built up based on the data we do know like company, title, location, etc. We could also possibly limit the job description twitter style: straight up plain text-area input with a character limit. Give us the elevator pitch :D

**Comment by danhannigan** [comment]
I forgot to clarify one kind of concept I've had in my head is that since we're basically just asking folks to share links to job posts where they've already done the work of adding a description/formatting and stuff I don't want to have them feel like they need to replicate that work here — even if it would be a copy + paste job — if that makes sense? Hence leaning a bit more towards simplicity. But I can be swayed one way or the other!

**Comment by ChaseDudas** [comment]
I think we should hold off on edit access for now, at least in this issue. I think that will help to reduce the complexity inside this issue.

> As far as the page SEO description... I think simplicity is our friend here so yeah some standard string that gets built up based on the data we do know like company, title, location, etc.

I agree with the idea of a simple page SEO description using the data we already have.

> We could also possibly limit the job description twitter style: straight up plain text-area input with a character limit. Give us the elevator pitch

I like siding more towards simplicity and bringing in complexity as needed. This idea reminds me of how #job-board in Discord is currently working. There is something fun and creative about giving us the elevator pitch.

**Comment by ChaseDudas** [comment]
**Features being implemented**
Build a page for each job so it has its own unique URL + SEO
Simple SEO page description using data we already have
Allow for a brief description of the job ( Twitter style. Text-area input with char limit. Give us your elevator pitch! )

Does that capture everything so far?

**Comment by ChaseDudas** [comment]
Oh...I also forgot to ask if you had some designs in mind for the page already?

**Comment by danhannigan** [comment]
@ChaseDudas I do not! But I can pull something together pretty easily or just work with you on what I'm thinking. Happy to proceed either way

**Comment by danhannigan** [comment]
Hey that looks good! There are a few small tweaks I'd wanna make but I can do that after you get it worked up, I can go ahead and tackle the output on mobile, too! 

Thanks for taking the time to do that! Nice work!

**Comment by ChaseDudas** [comment]
Sweet! Yea, mobile would be excellent. Right now, it just flexes and looks very similar on mobile.

@danhannigan It has been a sec since I have worked using issues in GitHub (currently using Jira). I am not seeing the option to create a branch off this issue. Do I need permission to create a branch? Thanks for the help 😃

**Comment by danhannigan** [comment]
![Screen Shot 2022-05-19 at 9 45 46 AM](https://user-images.githubusercontent.com/1581290/169341797-53df287f-7ef8-4a01-9ef2-5396ce57ccf3.png)

@ChaseDudas ah shoot, do you not see that option in the right hand sidebar of the issues page?
